"""Project-wide environment variable names and grouped aliases."""

from __future__ import annotations

ENV_PYCLAW_STATE_DIR = "PYCLAW_STATE_DIR"
ENV_OPENCLAW_STATE_DIR = "OPENCLAW_STATE_DIR"
ENV_PYCLAW_CONFIG_PATH = "PYCLAW_CONFIG_PATH"
ENV_OPENCLAW_CONFIG_PATH = "OPENCLAW_CONFIG_PATH"
ENV_PYCLAW_GATEWAY_PORT = "PYCLAW_GATEWAY_PORT"
ENV_OPENCLAW_GATEWAY_PORT = "OPENCLAW_GATEWAY_PORT"
ENV_PYCLAW_GATEWAY_URL = "PYCLAW_GATEWAY_URL"

ENV_PYCLAW_AUTH_TOKEN = "PYCLAW_AUTH_TOKEN"
ENV_OPENCLAW_AUTH_TOKEN = "OPENCLAW_AUTH_TOKEN"
ENV_PYCLAW_GATEWAY_TOKEN = "PYCLAW_GATEWAY_TOKEN"
ENV_OPENCLAW_GATEWAY_TOKEN = "OPENCLAW_GATEWAY_TOKEN"
ENV_PYCLAW_GATEWAY_PASSWORD = "PYCLAW_GATEWAY_PASSWORD"
ENV_OPENCLAW_GATEWAY_PASSWORD = "OPENCLAW_GATEWAY_PASSWORD"

ENV_PYCLAW_DISABLE_BONJOUR = "PYCLAW_DISABLE_BONJOUR"
ENV_PYCLAW_TEST = "PYCLAW_TEST"
ENV_PYCLAW_MDNS_HOSTNAME = "PYCLAW_MDNS_HOSTNAME"
ENV_CLAWDBOT_MDNS_HOSTNAME = "CLAWDBOT_MDNS_HOSTNAME"
ENV_PYCLAW_TEST_TAILSCALE_BINARY = "PYCLAW_TEST_TAILSCALE_BINARY"

AUTH_TOKEN_ENV_VARS = (ENV_PYCLAW_AUTH_TOKEN, ENV_OPENCLAW_AUTH_TOKEN)
GATEWAY_TOKEN_FALLBACK_ENV_VARS = (
    ENV_PYCLAW_GATEWAY_TOKEN,
    ENV_PYCLAW_AUTH_TOKEN,
    ENV_OPENCLAW_GATEWAY_TOKEN,
    ENV_OPENCLAW_AUTH_TOKEN,
)
GATEWAY_PASSWORD_ENV_VARS = (ENV_PYCLAW_GATEWAY_PASSWORD, ENV_OPENCLAW_GATEWAY_PASSWORD)
